name: at_contacts_group_flutter
description: A Flutter plugin project to provide group functionality with contacts using @â€Žplatform.
version: 3.0.3
homepage: https://atsign.dev
repository: https://github.com/atsign-foundation/at_widgets

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.0.8
  file_picker: ^4.2.3
  emoji_picker_flutter: ^1.0.8
  flutter_slidable: ^0.6.0
  flutter_image_compress: ^1.1.0
  pedantic: ^1.11.0
  flutter_toastr: ^1.0.2

  # desktop - dependencies
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.3

  at_client_mobile: ^3.1.1
  at_commons: ^3.0.0
  at_common_flutter: ^2.0.2
  at_contacts_flutter: ^3.0.2
  at_contact: ^3.0.1
  
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

dependency_overrides:
  plugin_platform_interface: ^2.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_contacts_group_flutter
        pluginClass: AtContactsGroupFlutterPlugin
      ios:
        pluginClass: AtContactsGroupFlutterPlugin
      macos:
        default_package: at_contacts_group_flutter
      windows:
        default_package: at_contacts_group_flutter
      linux:
        default_package: at_contacts_group_flutter

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/empty_group.png
    - assets/images/send.png
    # - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
