name: at_onboarding_flutter
description: A Flutter plugin project for onboarding any @‎sign in @‎platform
  apps with ease. Provides a QRscanner option and an upload key file option to
  authenticate.
version: 3.0.0
homepage: https://atsign.dev
repository: https://github.com/atsign-foundation/at_widgets

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  archive: ^3.1.2
  at_backupkey_flutter: ^3.0.0
  at_client: ^3.0.0
  at_client_mobile: ^3.0.0
  at_commons: ^3.0.0
  at_server_status: ^1.0.3
  at_utils: ^3.0.0
  file_picker: ^4.0.0
  flutter:
    sdk: flutter
  flutter_qr_reader: ^1.0.5
  http: ^0.13.3
  path_provider: ^2.0.2
  permission_handler: ^8.1.1
  pin_code_fields: ^7.2.0
  url_launcher: ^6.0.6
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
#dependency_overrides:
#  at_utils: ^3.0.0
#  at_lookup: ^3.0.0
#  at_client_mobile:
#    git:
#      url: https://github.com/atsign-foundation/at_client_sdk.git
#      path: at_client_mobile
#      ref: trunk
#  at_client:
#    git:
#      url: https://github.com/atsign-foundation/at_client_sdk.git
#      path: at_client
#      ref: trunk
#  at_commons:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_commons
#      ref: trunk
#  at_backupkey_flutter:
#    git:
#      url: https://github.com/atsign-foundation/at_widgets.git
#      path: at_backupkey_flutter
#      ref: trunk

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_onboarding_flutter
        pluginClass: AtOnboardingFlutterPlugin
      ios:
        pluginClass: AtOnboardingFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
