name: at_location_flutter
description: A Flutter plugin project to share locations between two @â€Žsigns and track them on OSM (OpenStreetMap).
version: 3.1.5
homepage: https://atsign.dev
repository: https://github.com/atsign-foundation/at_widgets/tree/trunk/at_location_flutter
issue_tracker: https://github.com/atsign-foundation/at_widgets/issues
documentation: https://atsign.dev/docs/functional_architecture/libraries/#at_location_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  latlong2: ^0.8.1
  positioned_tap_detector_2: ^1.0.4
  transparent_image: ^2.0.0
  async: ^2.8.2
  flutter_image: ^4.1.0
  cached_network_image: ^3.2.0
  path_provider: ^2.0.9
  vector_math: ^2.1.1
  proj4dart: ^2.0.0
  meta: ^1.7.0
  geolocator: ^8.2.1
  sliding_up_panel: ^2.0.0+1
  http: ^0.13.4
  fluttertoast: ^8.0.9

  # at_chat_flutter: ^2.0.2
  at_client_mobile: ^3.1.18
  at_lookup: ^3.0.26
  at_commons: ^3.0.18
  at_contact: ^3.0.7
  at_utils: ^3.0.10
  at_client: ^3.0.28
  at_common_flutter: ^2.0.8
  at_contacts_flutter: ^4.0.5


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_location_flutter
        pluginClass: AtLocationFlutterPlugin
      ios:
        pluginClass: AtLocationFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/at_location_flutter/assets/images/empty_group.png

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
